name: Go
on:
  push:
    tags:
      - /^v\d+\.\d+\.\d+$/
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build Linux Binary
      run: GOOS=linux GOARCH=amd64 VERSION=`git describe --tags --abbrev=0` go build -ldflags "-X main.Version=$VERSION" -o workspace/artifacts/gangway_linux_amd64
